services:
  nginx:
      container_name: weyra-talent-nginx
      image: nginx:1.25.3-perl
      ports:
        - 3000:3000
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        - ./nginx/certs:/etc/nginx/certs:ro
      depends_on:
        - api
  api:
    container_name: weyra-talent-api
    depends_on:
      - db
      - minio
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: ["npm", "run", "dev"]
    ports:
      - 8000:3000
      - 9229:9229
    env_file:
      - .env.docker
  db:
    container_name: weyratech-db
    image: postgres:16.2
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_EXTENSIONS: uuid-ossp pgcrypto
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/docker-init-scripts:/docker-entrypoint-initdb.d
  minio:
    container_name: weyratech-minio
    image: minio/minio:latest
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    env_file:
      - .env
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
  minio_data: