services:
  db:
    container_name: weyratech-db
    image: postgres:16.2
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_EXTENSIONS: uuid-ossp pgcrypto
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/docker-init-scripts:/docker-entrypoint-initdb.d
volumes:
  db_data: